### ISSUE TITLE
Runing the Project in local machine after cloning

### ISSUE THREAD

**Issue by NimmiW** [WorldBrain/Research-Engine#104]
Hi all,

I am new to WorldBrain

The issue I am currently having is cloning the repo to local machine. It would be great if anyone can give clue.

I am a windows user.

What I did was:
I cloned the project.
npm install -g browserify
npm install -g watchify 
npm install

However when I am running 'npm run watch' I get errors.

Error I am getting is 
![image](https://cloud.githubusercontent.com/assets/26009680/23454479/61f5a0ac-fe92-11e6-9006-16eead589aa4.png)

So I cannot build the project.

Thanks in advance :)

**Comment by obsidianart** [comment]
can you run ```node -v``` and let us know the version?

**Comment by NimmiW** [comment]
@obsidianart  here is my node verson v6.9.3

**Comment by obsidianart** [comment]
I think it might be a problem with mkdir or another command. I'm not used to windows but I remember there is also a power shell and the ubuntu shell, I would probably try to run in one of them. Let us know

**Comment by NimmiW** [comment]
ok @obsidianart . yes in windows, we use powershell.

**Comment by Prathiksha01** [comment]
I faced the same problem on Ubuntu. Not able to run the code locally. 
Node version - 7.4.0

**Comment by obsidianart** [comment]
if you can run with --verbose it might have more informations about the problem

**Comment by blackforestboi** [comment]
can you also not build it? `npm run build` ?

If not, its actually not so important to understand how the code currently works in the Research-Engine.
If you want to contribute, the best thing is to get familiar with the feature set that the WorldBrain extension already offers, means installing it (maybe then through the chrome store) and playing around with it. Don’t waste to much time on the current code itself, as we are currently in the process of refactoring the code and porting all the features to the [WebMemex](https://github.com/WebMemex/webmemex-extension), a project we merge the tool with at the moment.

Hope that helps!

**Comment by NimmiW** [comment]
@oliversauter  ok olive we will play with the extension and explore it
