### ISSUE TITLE
Special characters are not recognised for imported websites

### ISSUE THREAD

**Issue by blackforestboi** [WorldBrain/Research-Engine#106]
When regularly visiting documents, those pages are properly indexed and there is no problem with those characters.

But when the pages are imported there are special characters deleted. (i.e. chinese signs, or things like é, à, ö, ü, etc. )
The file that is responsible for analysing the HTML code and reading out only the text to be stored is this one: https://github.com/WorldBrain/Research-Engine/blob/master/src/js-browserify/html.js#L26

Can be tested by going the following steps:
1. Install the extension with a new chrome user (so that the DB is empty)
2. Deactivate the extension
3. visit: http://worldcrm.org/
3. Visit: https://en.wikipedia.org/wiki/French_Revolution
4. Re-Activate the extension
4. Import history 
5. Search for "資訊"
5. Search for "Ancient Régime"
6. Both searches have to be successful.

**Comment by reficul31** [comment]
I would like to take up this issue. As I am currently a bit confused with what exactly is happening I can't mention a plan of action. I will run the test given by @oliversauter and try to experiment a bit and get back to you.

**Comment by blackforestboi** [comment]
I updated the description, does that help more?

What is unclear to you?

**Comment by reficul31** [comment]
Thanks a lot @oliversauter for the clear description. Actually I understood the issue, but currently having trouble regarding some of the features of the plugin(Like history not importing and all the import of bookmarks failing). Currently I am trying to figure out a hack to get around them. Will report back as soon as possible.'
Sorry for the late reply.

**Comment by blackforestboi** [comment]
Try to rebase with the latest master, there everything should work again.

**Comment by blackforestboi** [comment]
closed with #112
