### ISSUE TITLE
Search keywords are case sensitive?

### ISSUE THREAD

**Issue by luboq** [WorldBrain/Research-Engine#117]
I think case-insensitive is better!

![](http://onuia4d7l.bkt.clouddn.com/2017_05_04_999.gif)

**Comment by blackforestboi** [comment]
Hey @waldens 

Thanks a lot for taking so much time to do the screencast and highlight everything. Indeed case-insensitive would be way better here. Very much appreciated!

[With the new version we currently work on](https://github.com/WorldBrain/WebMemex), you will be able to delete your history directly from the search results, hence this way of searching entries is not necessary anymore. 

For that reason, it might not be worth it to fix the issue for now. 
Therefore I would close this issue and notify you as soon as the new version is out. 

Enjoy your weekend!
