### ISSUE TITLE
Make diagram and write explanation for current architecture

### ISSUE THREAD

**Issue by blackforestboi** [WorldBrain/Research-Engine#20]
Make a chart of how the current tool processes data and explain the processes. 

Should be done by @arpitgogia and @oliversauter because they built the first version and saw how the code works.

**Comment by blackforestboi** [comment]
#### Problems we encountered:
- Parser cannot extract all visible text from website when HTML code is not coming from the rendering of browser. (document.body.innerContent)

#### Please try to find answers to the following questions.
- Can we query the existing database?
- Can we easily add fields?

**Comment by bohrium272** [comment]
The existing database is `localStorage` so we can definitely query it.

**Comment by blackforestboi** [comment]
ok, and how? We have to be able to query it like an SQL DB. 

for example, If i want to have all the columns for a url, how can I do this?
currently the primary key that is used to store the the URLs is the timestamp.

**Comment by bohrium272** [comment]
`localStorage` is purely key based, so we can store JSON objects then query them.

**Comment by blackforestboi** [comment]
ok thats good news. So we can extend the data also for all of the urls easily?

How would such a query look like, if want to have for example the timestamp for a url?

**Comment by bohrium272** [comment]
```
chrome.storage.local.get(time, function(data){
     console.log(data['time']);
}
```

**Comment by blackforestboi** [comment]
mhh, and how is the specific url defined here? So lets say I visited this url: https://blog.mousereeve.com/technologies-of-the-decentralized-web-summit/

And later I want to get the time stamp of it?

**Comment by bohrium272** [comment]
We'll have to change the key with which we store the item. After that it's just a JSON object with a timestamp field.

**Comment by blackforestboi** [comment]
mhh, and how is it if we deploy another search system? maybe elastic or lucene? Then we must be able to identify elements with more than just the key, correct?

**Comment by bohrium272** [comment]
Keep in mind we are constrained by what Chrome and JavaScript can use. Don't think elastic search is available for the front end.

**Comment by blackforestboi** [comment]
yes, thats indeed a little bit of a problem with developing extensions. 

So what we need is a storage system that allows us to perfom better queries and indexing even in local storage. 

It is still not very transparent to me, how the current storage system works.

**Comment by blackforestboi** [comment]
Thanks to @arpitgogia for the overview
![](https://docs.google.com/drawings/d/1hSZCXTmbGRGFzgclqIC4u4Htf-OrrIfKyU_eucWxeB4/pub?w=1069&h=721)

**Comment by blackforestboi** [comment]
I made another architecture chart for the tool as it stands today (see PR #27) 
![](https://docs.google.com/drawings/d/1tHnbod9t2u3XfRQ0QPS8B4JufIEC4Lqs231bW2bcXzY/pub?w=2442&h=1176)

@arpitgogia @dvigneshwer @amitkumarj441 could you check if this is correctly displayed by following the processes of the tool?
