### ISSUE TITLE
Malware Warning stops upload of bookmarks (Chrome)

### ISSUE THREAD

**Issue by BirgitPohl** [WorldBrain/Research-Engine#40]
Google Chrome: 54.0.2840.98 (64-bit)

Include aknewelt or another page that has a malware flag of Chrome into your bookmarks
<img width="402" alt="bildschirmfoto 2016-11-25 um 17 45 20" src="https://cloud.githubusercontent.com/assets/4340405/20707849/8732f91c-b62d-11e6-8850-cdbf0f1161f6.png">

Start bookmark upload.
A malware warning comes as a popup, or even as a page redirect.

**Expected result:** Warning comes, it will put this particular page on hold. But won't stop any other bookmarks to upload.
**Another expected result:** Browser needs to notify user that upload has been stopped.
**Actual result:** Warnung stops the upload - without the user notifying)

**Comment by blackforestboi** [comment]
What kind of warning is it? Can you give a screenshot for that as well?
How did you know that it stopped the download?

I still could not reproduce the problem. Maybe its not flagged for me or so.

**Comment by blackforestboi** [comment]
@BirgitPohl can you check now if the problem still persists with the update?
Thaaanks :)

**Comment by blackforestboi** [comment]
@BirgitPohl Can you give a short feedback if it now work? Thanks! :)

**Comment by blackforestboi** [comment]
I take it as solved.
