### ISSUE TITLE
Welcome Page not showing after extension installation

### ISSUE THREAD

**Issue by danrl** [WorldBrain/Research-Engine#45]
After installation the URL `chrome-extension://[random]/assets/about.html` says:

> Your file was not found
> 
> It may have been moved or deleted.
> ERR_FILE_NOT_FOUND

The favicon(?) is shown, so there must be something. Refresh doesn't help. Extension was installed successfully and is usable, too. Not a big but, then. However, this is reproducible.

Chrome Version 54.0.2840.98 (64-bit) on macOS. Same issue on Version 55.0.2883.75 (64-bit) on macOS (latest).

**Comment by blackforestboi** [comment]
Mhh, ok I just saw that the about.html was named About.html....Could this be the problem?
About to update the tool with that.

**Comment by blackforestboi** [comment]
I actually could not reproduce the problem :/
on version :Version 55.0.2883.75 (64-bit)

**Comment by danrl** [comment]
It's a minor bug. Will try with a vanilla chrome later and let you know the results.

**Comment by danrl** [comment]
> Mhh, ok I just saw that the about.html was named About.html....Could this be the problem?
> About to update the tool with that.

`About.html` -> `about.html` fixes it.

**Comment by blackforestboi** [comment]
ok done, goes out with the next update.

**Comment by blackforestboi** [comment]
Thanks for pointing to this :)

**Comment by danrl** [comment]
Affects only systems with case-sensitive filesystems. How did you fix it? Mind pushing the related commit for testing?

**Comment by blackforestboi** [comment]
I just renamed the file from `About.html` to `about.html` 

pushed the commits here: https://github.com/WorldBrain/Research-Engine/pull/44/commits

**Comment by danrl** [comment]
I think we should consider TDD, this is a typical bug that could be squashed with unit tests.

Not very easy, but maybe for the business logic we should invest in that.

* http://stackoverflow.com/questions/2869827/how-to-test-chrome-extensions
* http://stackoverflow.com/questions/14798528/testing-browser-extensions

**Comment by blackforestboi** [comment]
Yeah, testing is completely neglected at the moment and I don't have experience with it. But happy to get into it. Will read! Thanks!

I also read about browserify being an option to implement Node.js testing frameworks? Do you know about that?
