### ISSUE TITLE
Port it to Edge 

### ISSUE THREAD

**Issue by Droyk** [WorldBrain/Research-Engine#62]
what do you think? & rightnow there is no way to add it on the store manually you have to talk to the microsoft dev. to add your extension on the store.

**Comment by blackforestboi** [comment]
Microsoft Edge is a little bit of a pain, as they [do not support the Web Extension convention](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/extension-api-roadmap/). (or not that many API features at all)
Means we would have to develop a completely separate extension to make it work there. (if we manage to do that at all)

More likely is that we write a native application for the Mac and Win that takes the necessary data from the local system and only has a very limited Edge Extension to communicate some of the data. 

Thanks for your many inputs so far. Really appreciate it!

**Comment by blackforestboi** [comment]
closed for now, as not on any foreseeable roadmap, can reopen anytime.
