### ISSUE TITLE
More sensible blacklist URL match modes + regex support

### ISSUE THREAD

**Issue by pointyointment** [WorldBrain/Research-Engine#69]
Currently, for blacklisting, I can choose between "specific page", "entire site", and "all URLs containing" for each filter I add. "Specific page" sounds like it blacklists the exact URL I enter, and nothing else. "All URLs containing" sounds like it blacklists any URL that contains the string I enter. "Entire site", though, I'm not sure about. In "entire site" mode, does a filter for `example.com` also block `www.example.com`, `www.example.com/page.html`, `wiki.example.com`, etc., or only `example.com` and `example.com/page.html` without the `www`? What about `https://example.com` vs. `http://example.com`?

What I think would solve this ambiguity is having URL match mode options more similar to [Stylish](https://en.wikipedia.org/wiki/Stylish)'s. Stylish's options are exact whole-URL match, URLs starting with the string, URLs on the domain entered (the wording of which solves the "what does 'entire site' mean?" ambiguity described above), and URLs matching the regular expression entered.

That brings me to my second request: I think it would be useful to allow blacklisting by regular expressions. There are some sites I want to blacklist only certain parts of, while still allowing other parts of, that are very difficult or impossible to do with the current options due to the way their URLs are structured. Regular expressions would make it easy. I presume it would be possible to implement it exactly the same way Stylish has done, which I assume is to use JavaScript's built-in regex engine.

**Comment by blackforestboi** [comment]
Hey @pointyointment 

thanks for taking the time for your lengthy input!

You are right, it's really quite ambiguous.
This part is legacy code from the project we forked the original history functionality from.
The descriptions are actually switched, will change that in the next release.

**Wording right now:**
"entire website"  = just the URL
"specific page"  = the whole domain
"All urls containing" is basically the Regex you are looking for. 

**What I will switch it to** (thoughts?)
"Only this exact url" = just the url listed
"all pages on the domain" = the whole domain
"all urls containing this text (Regex)" = Regex

**Comment by blackforestboi** [comment]
Updated Extension, already in chrome store. When you [force update](http://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/) the extension, this change is already usable. 

Thanks for your input!
