### ISSUE TITLE
A more user-friendly kind of exclude this site feature implementation 

### ISSUE THREAD

**Issue by Droyk** [WorldBrain/Research-Engine#72]
So I thought that there should be a more user-friendly and more efficient way to Exclude the site so my fav. extension come to my mind uBlock Origin they actually have a most efficient way to exclude the site. 

See the below image to know more 
![screenshot_20161209103843](https://cloud.githubusercontent.com/assets/15848350/21078250/524a4484-bf8e-11e6-86ab-3b4e4f712985.png)

**thanx for reading it**

**Comment by blackforestboi** [comment]
Good idea, is on the list VERY soon. Blacklisting now is quite a pain. 

Close this issue though, because its a duplicate/addition to #46
