### ISSUE TITLE
There is no clickable url on Preferences > history > stored pages nor there is anyway to know the full url of the stored page

### ISSUE THREAD

**Issue by Droyk** [WorldBrain/Research-Engine#73]
I don't know why this hasn't been implemented yet!!  

![image](https://cloud.githubusercontent.com/assets/15848350/22059884/b0ebb88c-dd94-11e6-846d-27815fbae902.png)

**Comment by obsidianart** [comment]
Note: add title attribute and insert the full url there

**Comment by blackforestboi** [comment]
I already fixed it by making the short text clickable with a link to it. 
So no need to display full title.

See here in this commit: 
https://github.com/WorldBrain/Research-Engine/commit/5ebac218aa6d40bc922963383c01d3c423907448

Will be live with next update!

Thanks @Droyk for the remark!
