### ISSUE TITLE
Sometimes CSS is not loaded correctly - page needs to be reloaded then. 

### ISSUE THREAD

**Issue by blackforestboi** [WorldBrain/Research-Engine#80]
Sometimes the CSS of the dashboard is not loaded correctly, results in a barebone view. 
Page then needs to be reloaded. Annoying. 

See here:
http://recordit.co/qhT4vdoYeI

**Comment by aquibm** [comment]
Hey,

I could not reproduce this issue using either of the production (from the chrome store) or dev builds. If you're able to consistently reproduce it, could you please check if any errors are being reported in the developer console (F12)

Cheers,
Aquib.

**Comment by blackforestboi** [comment]
<img width="562" alt="screen shot 2017-01-21 at 20 00 43" src="https://cloud.githubusercontent.com/assets/7870039/22176912/597d89cc-e014-11e6-98ed-2141d136c6b9.png">

**Comment by blackforestboi** [comment]
I had this problem a couple of times, but could reproduce it the most, if I used a mac screenrecorder ...weirdly.

**Comment by blackforestboi** [comment]
could not be reproduced
