### ISSUE TITLE
Incorrect link to blacklisted sites in Preferences

### ISSUE THREAD

**Issue by paddylandau** [WorldBrain/Research-Engine#83]
In the Preferences page, there is the following instruction.

> All major American banks are already blacklisted. To see a list, visit our [GitHub repository](https://github.com/WorldBrain/Research-Engine/blob/master/extension/js/blacklist2.js).

This link leads to a 404 Not Found page. I believe that the correct URL is:

https://github.com/WorldBrain/Research-Engine/blob/master/src/js/blacklist2.js

Incidentally, you might also want to update your [blacklist FAQ](https://www.reddit.com/r/WorldBrain/comments/5m80qw/how_do_i_blacklist_pages/) to indicate two options instead of three.

Thank you

**Comment by blackforestboi** [comment]
Hey Paddy!

Thanks for the notice. Fixed in https://github.com/WorldBrain/Research-Engine/commit/b0471b52f74d9b0799f63597f8614bb731216a99

**Comment by blackforestboi** [comment]
Alongside with the default blacklist option you sent me via mail!

Feel free to post as many issues anytime. Then we can discuss them here. 
If we make mistakes we should be open about it anyway :)

**Comment by blackforestboi** [comment]
Hey Paddy, 

I just found out that there are huge performance issues with the default blacklist. So I had to remove it again. We will include it later again, but for now you have to blacklist your bank separately!

Thanks!
Oliver

**Comment by paddylandau** [comment]
OK, Oliver, that's perfectly understandable.

Manual blacklist it is!

Warmly

Paddy
