### ISSUE TITLE
Kicked by Google while importing history

### ISSUE THREAD

**Issue by crazy-max** [WorldBrain/Research-Engine#84]
Seems legit :neutral_face:

![image](https://cloud.githubusercontent.com/assets/1951866/22212207/115252b8-e190-11e6-83ce-7bc6ff9c89f7.png)
```
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.
```

Maybe scatter google search queries during the import would solved this issue ?

**Comment by blackforestboi** [comment]
Hey @crazy-max 

thanks for taking the time to report this issue.

Oh you perform a lot of google searches it seems :)
Did it stop your download or returned failed downloads?

Yes thats a good idea, let me check how we could do this. 
Maybe we find a work around for now, when I know more about how the work flow of your error is. 

Have a good start into the week!
- Oliver

**Comment by crazy-max** [comment]
Hi @oliversauter

In fact i made duckduckgo then google searches if duckduckgo have not the expected results.
I will send you asap my console logs.

Btw what type of queries the engine does? HEAD or full body?
If it's a full body maybe:

- use only HEAD + some meta queries
- or use an alternate useragent (googlebot ?)

Maybe this will solve the issue too.

And thanks for this indepth tool :)

**Comment by blackforestboi** [comment]
> Btw what type of queries the engine does? HEAD or full body?

If you visit a page, it grabs the text with `document.body.innerText`, when importing its an XMLHTTP request, where it grabs the whole HTML code and strips out the visible text via textract().

And then in both cases it stores the data in localstorage and indexes it for search. 

We are currently in a major refactoring and afterwards we can take on these optimisations. 

In any case, thanks a lot for your ideas here. Very much appreciated.

**Comment by crazy-max** [comment]
I was not able to reproduce the exact behavior. I've got some captcha like the other time after some google searches but not the [initial message](https://github.com/WorldBrain/Research-Engine/issues/84#issue-202581584) :

> ![image](https://cloud.githubusercontent.com/assets/1951866/22228504/eb53a14c-e1d1-11e6-9219-91c30c33f97c.png)

Here is the console log :

> ![image](https://cloud.githubusercontent.com/assets/1951866/22228520/00509820-e1d2-11e6-9b58-20b062161887.png)

**Comment by blackforestboi** [comment]
Thanks for sharing.

Good news is_ we can recrawl the pages. It will just skip failed ones for now. 
When your import is finished and you restart the import, there should still be entries left. These are then only the google searchers. 

Means, as soon as we have solved the issue, you can just re-import them.
