### ISSUE TITLE
move compatability.js to lib

### ISSUE THREAD

**Issue by ShamariFeaster** [WorldBrain/Research-Engine#86]
Looking at the code base with fresh eyes, I'm initally just going throw out some suggestions based on mental roadblocks I've encountered in reading the code base. I'll start with this one. This code is basically a polyfill so it would seem lib/ would be a more appropriate place for it?

**Comment by blackforestboi** [comment]
Yeah, the code is currently quite messy...as you put it in lovely words: a polyfill :D
yes good idea, we are about to restructure basically everything. 

We want to make modules that are reusable. Many functions are now in the backgroundJS file that can be separated into different folders and files. 

For example one folder will be "parsers" there we collect all the different parsing files. This will be needed for later, as we add parsers for different websites, to get better results specifically for them (i.e. Asana)

Another one is imports, where we collect all the files that are responsible for import from somewhere. Here we put the files that import history/bookmarks and download_urls.js, that actually downloads urls from the web. 
Later the files that are drawing content from different APIs.

If you are up for that, we can have a skype call and go through the current code together and maybe already do some refactoring?

**Comment by blackforestboi** [comment]
You can find the work done regarding this here: https://github.com/WorldBrain/Research-Engine/tree/refactor-JS-background

**Comment by blackforestboi** [comment]
closing because done. The issue tracking this work is here: #56
