### ISSUE TITLE
Blacklist does not work with 'localhost'

### ISSUE THREAD

**Issue by blackforestboi** [WorldBrain/Research-Engine#88]

**Comment by bhagatparwinder** [comment]
Even though I have disabled the extension on **localhost**, I see the plugin tries to run. I saw to files throwing error. One was pdfWorker and the other is background.js (in Chrome console).

`Uncaught TypeError: Cannot read property 'onInputChanged' of undefined at chrome-extension://abkfbakhjpmblaafnpgjppbmioombali/js/background.js:28 (anonymous)`

**Comment by blackforestboi** [comment]
Hey @bhagatparwinder thanks for coming over from Product Hunt

The error message is known and does not cause a work flow problem.

To your blacklist issue: 
The blacklist just prevents the page from being stored, the plugin itself runs on every page.

To make sure: Do the pages with localhost turn up in the search results afterwards?

**Comment by bhagatparwinder** [comment]
That's what I thought. Blacklisting prevents indexing, but the extension is still running.
To answer your question, no **localhost** is not in the search anymore. This works for a normal end user but for a developer who lives in console all day, seeing unnecessary errors is not good. 😢

**Comment by blackforestboi** [comment]
ok, so I am happy that at least it does not cause a problem with the blacklist itself!

Yes agreed, errors suck! 
We are currently in a major refactoring of the code and afterwards this error should be gone as well :)

Would be great if you can give some feedback on the outcome of this issue to product hunt, so that people don't worry about the blacklist function not working properly. 

Thanks a lot!

**Comment by bhagatparwinder** [comment]
Absolutely, I'll clarify on PH. For now, this is not a bug 👍 

Maybe create a feature request 😄

**Comment by blackforestboi** [comment]
hehe Feature Request: "get rid of that damn error, it annoys me" :)
