### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by crazy-max** [WorldBrain/Research-Engine#89]
Hi,

For all links visited on Chrome 55.0.2900.1, i have this error in the console :

```
VM175:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.93../html.js (bundle.js:46646)
    at s (bundle.js:1)
    at e (bundle.js:1)
    at bundle.js:1
93../html.js @ bundle.js:46646
s @ bundle.js:1
e @ bundle.js:1
(anonymous) @ bundle.js:1
```

**Comment by blackforestboi** [comment]
Hello Max!

Thanks for pointing that out!

Yes we know about this error message, but it doesnt affect the functionality of the software.
At least as far as we know. Do you experience bugs?

We are currently in a major refactoring and afterwards everything will be working without a message. 

Have a good day!
Oliver

**Comment by crazy-max** [comment]
Hi Oliver,

I don't experience any bug, it's just for pointing that out.

Can't wait for a new release!

Bye!

**Comment by spookyuser** [comment]
Also getting this error. It's not really a problem just cluttering up the console :P
