### ISSUE TITLE
Cannot read property 'onInputChanged' of undefined

### ISSUE THREAD

**Issue by crazy-max** [WorldBrain/Research-Engine#90]
Hi,

For all links visited on Chrome 55.0.2900.1, i have this error in the console :

```
background.js:28 Uncaught TypeError: Cannot read property 'onInputChanged' of undefined
    at background.js:28
(anonymous) @ background.js:28
```

**Comment by blackforestboi** [comment]
Same goes here.

We know about this error message, but it doesnt affect the functionality of the software.

After the refactoring everything will be working without a message.

Have a good day!
Oliver

**Comment by crazy-max** [comment]
Ok thanks!
